<?php

$esPath = 'public/locales/es.json';
$enPath = 'public/locales/en.json';

$es = json_decode(file_get_contents($esPath), true);
$en = json_decode(file_get_contents($enPath), true);

$translations = [
    'report' => [
        'medicalRecordTitle' => ['es' => 'Historia Clínica', 'en' => 'Medical Record'],
        'recordNumber' => ['es' => 'Nº de Registro', 'en' => 'Record No.'],
        'consultDate' => ['es' => 'Fecha de Consulta', 'en' => 'Consultation Date'],
        'generalInfo' => ['es' => 'Información General', 'en' => 'General Information'],
        'anamnesisAndVitals' => ['es' => 'Anamnesis y Signos Vitales', 'en' => 'Anamnesis & Vital Signs'],
        'reasonForVisit' => ['es' => 'Motivo de Consulta', 'en' => 'Reason for Visit'],
        'anamnesisSigns' => ['es' => 'Anamnesis y Signos Clínicos', 'en' => 'Anamnesis & Clinical Signs'],
        'physicalExamBySystem' => ['es' => 'Examen Físico por Sistemas', 'en' => 'Physical Exam by Systems'],
        'diagnosisAndPlan' => ['es' => 'Diagnóstico y Plan', 'en' => 'Diagnosis & Plan'],
        'diagnosis' => ['es' => 'Diagnóstico Presuntivo / Definitivo', 'en' => 'Presumptive / Definitive Diagnosis'],
        'treatmentIndications' => ['es' => 'Tratamiento e Indicaciones', 'en' => 'Treatment & Medical Indications'],
        'prescriptions' => ['es' => 'Receta Médica', 'en' => 'Prescription'],
        'medication' => ['es' => 'Medicamento', 'en' => 'Medication'],
        'dose' => ['es' => 'Dosis', 'en' => 'Dose'],
        'frequency' => ['es' => 'Frecuencia', 'en' => 'Frequency'],
        'additionalNotes' => ['es' => 'Notas Adicionales', 'en' => 'Additional Notes'],
        'generatedBy' => ['es' => 'Documento generado automáticamente por', 'en' => 'Document automatically generated by'],
        'confidentiality' => ['es' => 'Este reporte es de uso exclusivamente clínico y confidencial.', 'en' => 'This report is for strictly clinical and confidential use.'],
        'completeHistory' => ['es' => 'Historial Clínico Completo', 'en' => 'Complete Medical History'],
        'totalRecords' => ['es' => 'Total registros', 'en' => 'Total records'],
        'attendedBy' => ['es' => 'Atendido por', 'en' => 'Attended by'],
        'noRecords' => ['es' => 'No hay registros clínicos para esta mascota.', 'en' => 'No clinical records found for this pet.'],
        'medicalReport' => ['es' => 'Reporte Médico Clínico', 'en' => 'Clinical Medical Report'],
        'downloadPDF' => ['es' => 'Descargar PDF', 'en' => 'Download PDF'],
    ],
    'table' => [
        'patient' => ['es' => 'Paciente', 'en' => 'Patient'],
        'owner' => ['es' => 'Propietario', 'en' => 'Owner'],
        'phone' => ['es' => 'Teléfono', 'en' => 'Phone'],
        'veterinarian' => ['es' => 'Veterinario', 'en' => 'Veterinarian'],
        'reason' => ['es' => 'Motivo', 'en' => 'Reason'],
        'dateTime' => ['es' => 'Fecha y Hora', 'en' => 'Date & Time'],
        'client' => ['es' => 'Cliente', 'en' => 'Client'],
        'pet' => ['es' => 'Mascota', 'en' => 'Pet'],
        'status' => ['es' => 'Estado', 'en' => 'Status'],
        'date' => ['es' => 'Fecha', 'en' => 'Date'],
    ],
    'form' => [
        'species' => ['es' => 'Especie', 'en' => 'Species'],
        'breed' => ['es' => 'Raza', 'en' => 'Breed'],
        'gender' => ['es' => 'Sexo', 'en' => 'Gender'],
        'sex' => ['es' => 'Sexo', 'en' => 'Sex'],
        'male' => ['es' => 'Macho', 'en' => 'Male'],
        'female' => ['es' => 'Hembra', 'en' => 'Female'],
        'taxId' => ['es' => 'DNI/RUC', 'en' => 'Tax ID/DNI'],
        'idNumber' => ['es' => 'DNI / RUC', 'en' => 'Tax ID / DNI'],
        'age' => ['es' => 'Edad', 'en' => 'Age'],
        'email' => ['es' => 'Email', 'en' => 'Email'],
        'address' => ['es' => 'Dirección', 'en' => 'Address'],
        'addr' => ['es' => 'Dir.', 'en' => 'Addr.'],
        'weight' => ['es' => 'Peso', 'en' => 'Weight'],
        'weightLast' => ['es' => 'Peso (último)', 'en' => 'Weight (last)'],
        'temperature' => ['es' => 'Temperatura', 'en' => 'Temperature'],
        'heartRate' => ['es' => 'Frec. Cardíaca', 'en' => 'Heart Rate'],
        'respRate' => ['es' => 'Frec. Resp.', 'en' => 'Resp. Rate'],
        'bodyCondition' => ['es' => 'Cond. Corp', 'en' => 'Body Cond.'],
        'hydration' => ['es' => 'Hidratación', 'en' => 'Hydration'],
        'painLevel' => ['es' => 'Nivel Dolor', 'en' => 'Pain Level'],
        'cardiovascular' => ['es' => 'Cardiovascular', 'en' => 'Cardiovascular'],
        'digestive' => ['es' => 'Digestivo', 'en' => 'Digestive'],
        'lymphNodes' => ['es' => 'Linfonodos', 'en' => 'Lymph Nodes'],
        'mucous' => ['es' => 'Mucosas', 'en' => 'Mucous Membranes'],
        'musculoskeletal' => ['es' => 'Músculoesq.', 'en' => 'Musculoskeletal'],
        'neurological' => ['es' => 'Neurológico', 'en' => 'Neurological'],
        'eyesEars' => ['es' => 'Ojos/Oídos', 'en' => 'Eyes/Ears'],
        'skinCoat' => ['es' => 'Piel/Pelaje', 'en' => 'Skin/Coat'],
        'respiratory' => ['es' => 'Respiratorio', 'en' => 'Respiratory'],
        'urinary' => ['es' => 'Urinario', 'en' => 'Urinary'],
        'route' => ['es' => 'Vía', 'en' => 'Route'],
        'duration' => ['es' => 'Duración', 'en' => 'Duration'],
        'indications' => ['es' => 'Indicaciones', 'en' => 'Indications'],
        'recommendedNextAppt' => ['es' => 'Próxima Cita Recomendada', 'en' => 'Recommended Next Appointment'],
        'patientData' => ['es' => 'Datos del Paciente', 'en' => 'Patient Data'],
        'clinicalDetails' => ['es' => 'Detalles Clínicos de la Cita', 'en' => 'Clinical Details of Appointment'],
        'notAssigned' => ['es' => 'No asignado', 'en' => 'Not assigned'],
        'additionalNotes' => ['es' => 'Notas adicionales', 'en' => 'Additional Notes'],
        'generalInfo' => ['es' => 'Información General', 'en' => 'General Information'],
        'pet' => ['es' => 'Mascota', 'en' => 'Pet'],
        'owner' => ['es' => 'Propietario', 'en' => 'Owner'],
        'phone' => ['es' => 'Teléfono', 'en' => 'Phone'],
    ],
    'appointment' => [
        'titleSingular' => ['es' => 'Cita', 'en' => 'Appointment'],
        'voucher' => ['es' => 'Comprobante de Cita Médica', 'en' => 'Medical Appointment Voucher'],
        'apptNumber' => ['es' => 'Nº de Cita', 'en' => 'Appointment No.'],
        'scheduledDate' => ['es' => 'Fecha Programada', 'en' => 'Scheduled Date'],
        'status' => ['es' => 'Estado de la Cita', 'en' => 'Appointment Status'],
    ],
    'misc' => [
        'years' => ['es' => 'años', 'en' => 'years'],
        'days' => ['es' => 'días', 'en' => 'days'],
        'notSpecified' => ['es' => 'No especificado', 'en' => 'Not specified'],
        'unspecifiedMedication' => ['es' => 'Medicamento no especificado', 'en' => 'Unspecified Medication'],
        'veterinarian' => ['es' => 'Médico Veterinario', 'en' => 'Veterinarian'],
        'on_date' => ['es' => 'el', 'en' => 'on'],
        'generalInformation' => ['es' => 'Información General', 'en' => 'General Information'],
    ],
    'status' => [
        'programada' => ['es' => 'Programada', 'en' => 'Scheduled'],
        'pendiente' => ['es' => 'Pendiente', 'en' => 'Pending'],
        'confirmada' => ['es' => 'Confirmada', 'en' => 'Confirmed'],
        'en_progreso' => ['es' => 'En Progreso', 'en' => 'In Progress'],
        'completada' => ['es' => 'Completada', 'en' => 'Completed'],
        'cancelada' => ['es' => 'Cancelada', 'en' => 'Cancelled'],
        'emergencia' => ['es' => 'Emergencia', 'en' => 'Emergency'],
    ],
    'btn' => [
        'pdf' => ['es' => 'PDF', 'en' => 'PDF'],
        'downloadPdf' => ['es' => 'Descargar PDF', 'en' => 'Download PDF'],
        'downloadPDF' => ['es' => 'Descargar PDF', 'en' => 'Download PDF'],
    ]
];

foreach ($translations as $group => $items) {
    if (!isset($es[$group])) $es[$group] = [];
    if (!isset($en[$group])) $en[$group] = [];
    foreach ($items as $k => $vals) {
        $es[$group][$k] = $vals['es'];
        $en[$group][$k] = $vals['en'];
    }
}

file_put_contents($esPath, json_encode($es, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));
file_put_contents($enPath, json_encode($en, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));

echo "Translations updated successfully.\n";
